language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sundries' ]; then cd .. && eval "mv $currentfolder generator-sundries" && cd generator-sundries; fi

